export const ClassConstants = {
  GET_ALl_CLASS_REQUEST: 'GET_ALl_CLASS_REQUEST',
  GET_ALl_CLASS_SUCCESS: 'GET_ALl_CLASS_SUCCESS',
  GET_ALl_CLASS_FAILURE: 'GET_ALl_CLASS_FAILURE',

  ADD_CLASS_REQUEST: 'GET_ALl_CLASS_REQUEST',
  ADD_CLASS_SUCCESS: 'GET_ALl_CLASS_SUCCESS',
  ADD_CLASS_FAILURE: 'GET_ALl_CLASS_FAILURE',

  REMOVE_CLASS_REQUEST: 'REMOVE_CLASS_REQUEST',
  REMOVE_CLASS_SUCCESS: 'REMOVE_CLASS_SUCCESS',
  REMOVE_CLASS_FAILURE: 'REMOVE_CLASS_FAILURE',

  UPDATE_CLASS_REQUEST: 'UPDATE_CLASS_REQUEST',
  UPDATE_CLASS_SUCCESS: 'UPDATE_CLASS_SUCCESS',
  UPDATE_CLASS_FAILURE: 'UPDATE_CLASS_FAILURE',
};
