export const ExamConstants = {
  GET_EXAM_REQUEST: 'GET_EXAM_REQUEST',
  GET_EXAM_SUCCESS: 'GET_EXAM_SUCCESS',
  GET_EXAM_FAILURE: 'GET_EXAM_FAILURE',

  ADD_EXAM_REQUEST: 'ADD_EXAM_REQUEST',
  ADD_EXAM_SUCCESS: 'ADD_EXAM_SUCCESS',
  ADD_EXAM_FAILURE: 'ADD_EXAM_FAILURE',
};
