export const UserConstants = {
  SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'USERS_SIGNUP_FAILURE',

  SIGNIN_REQUEST: 'USERS_SIGNIN_REQUEST',
  SIGNIN_SUCCESS: 'USERS_SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'USERS_SIGNIN_FAILURE',

  SIGNOUT_REQUEST: 'SIGNOUT_REQUEST',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',

  UPDATE_PROFILE: 'UPDATE_PROFILE',
  UPDATE_PROFILE_FULLNAME: 'UPDATE_PROFILE_FULLNAME:',
  UPDATE_PROFILE_CLASS: 'UPDATE_PROFILE_CLASS',
  UPDATE_PROFILE_IMAGE: 'UPDATE_PROFILE_IMAGE',
  UPDATE_PROFILE: 'UPDATE_PROFILE:',
};
